### ISSUE TITLE
MSC-specific SKOS extension missing

### ISSUE THREAD

**Issue by SArndt-TIB** [runnwerth/MSC2020_SKOS#1]
Is the correct resource linked to the text highlighted in the picture?
It leads to http://msc2010.org/resources/MSC/2010/MSC2010 but this seems to contain metadata about the SKOS version of MSC 2010, not an ontology.
![grafik](https://user-images.githubusercontent.com/52701352/105479178-7313c700-5ca4-11eb-83f8-4531ad74ce57.png)

**Comment by SArndt-TIB** [comment]
This file may be recoverable. For the time being, there is a draft on the branch internalReferences.

**Comment by pdfion** [comment]
I have found two files with the name starting mscvocab after all.  They are attached here.  I have not checked them in any sense yet, or seen where they're called in my scripts.  Maybe these will help.  In fact, they were found in a directory with a README that runs
* msc2010-draft*.*: MSC2010 data files
  * *.skos - full SKOS; the rest is generated from that; the latest one is the master source of everything
  * *-nomath.rdf - MathML fragments removed
  * *-screen.xml - will display on-screen using CSS and XSL below in ../style
  * *.ttl - Turtle serialization
  * *.n3 - N3 serialization
  * *.nt - N-Triples form
  * *.trix - TriX form
* expand-skos-rules.n3: N3 rules that expand the core SKOS to the convenience version (dumbed down, suitable for follow-your-nose crawling)
* mscvocab.*: MSC-specific SKOS vocabulary extension
  * *.omn: master source (OWL Manchester)
  * *.owl: RDF/XML for deployment; generated with Protégé

So they are probably relevant.  I had to put the two files into a zip file or I couldn't attach by dragging below
[mscvocab.zip](https://github.com/runnwerth/MSC2020_SKOS/files/6112850/mscvocab.zip)

**Comment by SArndt-TIB** [comment]
Is it correct that some of the properties, datatypes and classes defined by the mscvocab.owl are not used in SKOS-representation of MSC 2010? ~~I wasn't able to find:~~ I got a clearer picture on this after a comparison between mscvocab-2010.ttl and our preliminary file, which I now updated according mscvocab-2010.ttl where appropriate. Here are the results (see also inline-comments in both files in commit https://github.com/runnwerth/MSC2020_SKOS/commit/aaa9b2b6c6e6707557fcbf1817f769ef39f82624)

| element | comment |
| ---  | ---  |
|~~mscvocab:changeNote~~| this actually refered to skos:changeNote, which can be imported from SKOS now|
| mscvocab:formerlyNote | is marked as deprecated, therefore not integrated to mscvocab-2020.ttl|
| mscvocab:forSource | owl:inverseOf  mscvocab:forSource, usage therefore not explicit; taken over to mscvocab-2020.ttl |
| mscvocab:string | used in an axiom on a datatype, taken over to mscvocab-2020.ttl |
| mscvocab:FormerlyNote | in the rdfs:range of a deprecated property, therefore not taken over to mscvocab-2020.ttl |
| MustUseScopeNote | there are individuals which seem to belong to this class - these are typed as skos:Concept though, e.g. http://msc2010.org/resources/MSC/2010/03-03-mustuseScopeNote, taken over to mscvocab-2020.ttl, not yet modelled in MSC 2020 SKOS, will become  its own issue |
|mscvocab:NotUseScopeNote | fitting individuals are present, e.g. http://msc2010.org/resources/MSC/2010/65J10-notuseScopeNote typed as skos:Concept |
|mscvocab:ScopeNote||
|mscvocab:SeeForLink| replaced by mscvocab:seeForStatement, modelled as a subclass of rdf:Statement |
| SemanticRelation | superordinate classe of mscvoca-2010 SeeForLink, modelled differently by re-using rdf:Statement for reified links | 
| mscvocab:UseScopeNote | individuals present, but typed as skos:Concept, taken over to mscvocab-2020.ttl, not yet modelled in MSC 2020 SKOS, will become  its own issue |

We are working with the other properties defined here, but we solve reification slightly differently. forSource and forTarget are both given but we declare seeFor-entitites as rdf:Statements and thus use rdf:subject and rdf:object to the name the source and the target of a statement. We use rdf:predicate to explicitly state the property of the direct links between forSource and forTarget (seeConditionally-triples).

**Comment by SArndt-TIB** [comment]
I uploaded the two files @pdfion provided to the folder oldMSC.

**Comment by SArndt-TIB** [comment]
The 2010 vewrsion is no longer missing and has been updated to a 2020 version.
