### ISSUE TITLE
seeFor-references for 00A69

### ISSUE THREAD

**Issue by SArndt-TIB** [runnwerth/MSC2020_SKOS#3]
seeFor-relations and seeFor-statements for 00A69 need to be added manually according to its scopeNote:

General applied mathematics \{For physics, see 00A79 and Sections 70-XX through 86-XX\}

**Comment by pdfion** [comment]
There are some manual interventions that will be needed.

**Comment by SArndt-TIB** [comment]
Do you have particular ones in mind or is this your general impression from the 2010 conversion? 
If you are referring to specific triples in the 2020 draft, then it would be great if you could go through these? Should we document these in sperate issues? That is probably too much overhead?

**Comment by SArndt-TIB** [comment]
> 
> 
> seeFor-relations and seeFor-statements for 00A69 need to be added manually according to its scopeNote:
> 
> General applied mathematics {For physics, see 00A79 and Sections 70-XX through 86-XX}

For clarification: Does this mean **all** of the following concepts **and all** their subconcepts? Looks very like it, I just wanna make sure before I add all of these relations and seeFor-Statements:

70 Mechanics of particles and systems
74 Mechanics of deformable solids
76 Fluid mechanics
78 Optics, electromagnetic theory
80 Classical thermodynamics, heat transfer
81 Quantum theory
82 Statistical mechanics, structure of matter
83 Relativity and gravitational theory
85 Astronomy and astrophysics
86 Geophysics


I'd add the direct seeCondtionally link via SPARQL:

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix msc: <http://msc.org/resources/MSC/msc2020/>
prefix mscvocab: <http://msc.org/resources/MSC/msc2020/mscvocab#>

construct {msc:00A69 mscvocab:seeConditionally ?x}
#select *
where {?x skos:broaderTransitive msc:70-XX}
```

**Comment by SArndt-TIB** [comment]
The solution suggested in #13 is the following:

```
###  http://msc.org/resources/MSC/msc2020/00A69
<http://msc.org/resources/MSC/msc2020/00A69> rdf:type owl:NamedIndividual ,
                                                      skos:Concept ;
                                             mscvocab:seeConditionally msc:PhysicsCollection ;
                                             skos:broader <http://msc.org/resources/MSC/msc2020/00Axx> ;
                                             skos:inScheme <http://msc.org/resources/MSC/msc2020/> ;
                                             skos:notation "00A69"^^xsd:string ;
                                             skos:prefLabel "General applied mathematics"@en ;
                                             skos:scopeNote "General applied mathematics \\{For physics, see 00A79 and Sections 70-XX through 86-XX\\}"@en .

###  http://msc.org/resources/MSC/msc2020/seeForStatement-00A69-to-PhysicsCollection
msc:seeForStatement-00A69-to-PhysicsCollection rdf:type owl:NamedIndividual ,
                                                        mscvocab:seeForStatement ;
                                               rdf:object msc:PhysicsCollection ;
                                               rdf:predicate mscvocab:seeConditionally ;
                                               rdf:subject <http://msc.org/resources/MSC/msc2020/00A69> ;
                                               mscvocab:scope "For physics"@en .

###  http://msc.org/resources/MSC/msc2020/PhysicsCollection
msc:PhysicsCollection rdf:type owl:NamedIndividual ,
                               skos:Collection ;
                      skos:member <http://msc.org/resources/MSC/msc2020/00A79> 
                      ### further members left out for the sake of their number
                      <http://msc.org/resources/MSC/msc2020/86-11> ;
                      skos:editorialNote "This collection does not have a skos:notation."@en ;
                      skos:prefLabel "physics collection"@en .

```

**Comment by SArndt-TIB** [comment]
The suggestion has been merged, so I'll close this.

**Comment by SArndt-TIB** [comment]
The suggested solution breaks the consistency of the MSC:

We cannot set a link between an instance of skos:Concept and a skos:Collection when the property used to do this (in this case mscvocab:seeConditionally) is a sub-property of skos:semanticRelation, since this implies that the object of the relation is a skos:Concept. Our actual object, however, is skos:Collection, which is disjoint with skos:Concept.

I will introduce a new (set) of properties which allows to link to a collection. and which is not a sub-property of skos:semanticRelation.
