### ISSUE TITLE
skos:Collections need to be completed

### ISSUE THREAD

**Issue by SArndt-TIB** [runnwerth/MSC2020_SKOS#4]
The MSC from 2010 contains several skos:Collections, which still need to be added to the 2020 version:

- [x] msc2010:ResearchExpositionCollection

- [x] msc2010:ProceedingsCollection

- [x] msc2010:GeneralReferenceWorksCollection

- [x] msc2010:ExplicitMachineComputationCollection

- [x] msc2010:InstructionalExpositionCollection

- [x] msc2010:HistoricalCollection

- [x] msc2010:ExperimentalCollection

- [x] msc2010:ComputationalMethodsCollection

**Comment by pdfion** [comment]
Yes those collections can be continued.  There is a possibility that one should add some collection to take account of the new general code slots that have been added.

**Comment by SArndt-TIB** [comment]
> 
> 
> Yes those collections can be continued. There is a possibility that one should add some collection to take account of the new general code slots that have been added.

Good point, I was actually wondering whether this is the case. Can you add those?

**Comment by SArndt-TIB** [comment]
Decision during call on 12th, March 2021:
If further collections are needed or wanted, please request them in seperate issues. This issue can be closed now.
